---
output: html_document
---

<br>
<h2>Welkom op het KCO Dashboard!</h1>
<br><br>
<i> KCO Dashboard </i> is een project van <a href="https://www.kenniscentrumongelijkheid.nl/">Kenniscentrum Ongelijkheid (KCO)</a> in samenwerking met <a href="https://www.eur.nl/en/ese/">Erasmus School of Economics (ESE)</a> over de sociaaleconomische ongelijkheid binnen de Metropoolregio Amsterdam. 

<b>Doel:</b> Het doel is het bijdrage aan het beschrijven, begrijpen en aanpakken van ongelijkheid binnen Amsterdam met beschrijvende statistiek.

<b>Hoe:</b> Met behulp van een interactief en intuïtief dashboard krijgt de gebruiker inzicht in de relatie tussen omstandigheden in de jeugd en ongelijkheid in uitkomsten voor individuen die zijn opgegroeid in Amsterdam.

<b>Wat:</b> Aan de hand van beschrijvende statistiek maken we inzichtelijk waar, wanneer en hoe ongelijkheid ontstaat en zich manifesteert in de Metropoolregio Amsterdam.

<br><br>
Vanuit het linkernavigatiepaneel heb je toegang tot de gradienten en staafdiagrammen over sociaaleconomische ongelijkheid binnen metropool Amsterdam. 

Dit dashboard bestaat uit:
<ul>
  <li>Gradienten</li>
  <li>Staafdiagrammen</li>
</ul>

<br><br>
Dit dashboard is gemaakt met [R Shiny](https://shiny.rstudio.com/). De code van dit dashboard is te vinden op [GitHub](https://github.com/Helenlam20/kco_dashboard). Voor meer inzicht over de kansenongelijkheid in Nederland, zie <a href="https://kansenkaart.nl/">KansenKaart.nl</a>.

Bekijk de onderstaande video voor een snelle walkthrough van het dashboard.

<br><br><br>
<iframe style = "display: block; margin: auto;" width="640" height="360" src="https://www.youtube.com/embed/Qu2J2ytWqxA?hd=1"></iframe>



