name: Deploy on DigitalOcean
on: [push]
jobs:
  
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: SSH 
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USERNAME }}
        key: ${{ secrets.SERVER_KEY }}
        port: ${{ secrets.SERVER_PORT }}
        script: |
          whoami
          ls -la
